### ISSUE TITLE
activerecord 6

### ISSUE THREAD

**Issue by cooldesigns** [janko/sinatra-activerecord#84]
it does not work

**Comment by joaocosta** [comment]
Specifically, following the example at https://learn.co/lessons/sinatra-activerecord-setup and running "rake -T", crashes with error message:

`LoadError: cannot load such file -- sinatra/activerecord/rake/activerecord_6`

Just copying sinatra/activerecord/rake/activerecord_5 to sinatra/activerecord/rake/activerecord_6 seems to fix it.
